jobs:
  include:
  - language: python
    python: 3.8
    script:
    - npm run python-install
  - language: node_js
    node_js:
    - 14
    services:
    - postgresql
    addons:
      postgresql: '10'
    dist: xenial
    notifications:
      email:
        on_success: change
        on_failure: always
    install:
    - npm ci
    before_script:
    - npm run build-client
    deploy:
      skip_cleanup: true
      provider: heroku
      app: yinsong01
      on:
        branch: master
      api_key:
        secure: RHTngL6+D9rhKsDRi/3NSfL/eT6Dzf+y74+15y+mvQXvDMx69SUJQa8j87qJc3Cd8uzEH1ITC8sO3yqNdLB2AQ62xEiLFvHRHWMyg8ZHmObtVoqHCXDb+Hdo8zjO9dW7bExDuwxqAlLpOUSCb/D6Y9wwYUF6qkVVBAlsmccYk6Mn8g5RzPK3paojs3be58BF3pp0m4jybZtkkQURsuBh893KCins37AFn33HdhsUFPNPvBKSbQJ6pYcj+ytoIUXkUdMKi49t8KpFLOSLbUU/MvY5UCbzj0A/EESb2au9IzWRjPyfbq64dS4ELkddk5BkpJxmfKOWia3MLnzFtl0itTU5hDDLcUadD59Jm49THQBIZ46eOHn1TCSlP53vSc2HXUnNVecHY9Lp9WGTMQOb5GeNV4RdfjDvRG4RirVj9ork9CREa2dxc9Usckq2cGo8uaWgZQMVUHTYF7E+ytTpmkU1utPE7J4IvQnNCnT+f4GhC4N5lcyiZIDffvk9kfQxl8C3jh5wKqStnCzBKStZxFqacGpR6IBfS1ljtqxP29zXAWeyFmUI1vaP3q5k8EOeRwt3OgtQx43ZnIzl5IPGb/6oSv7STgyCGqrwzyfY+koc/WdMcAcDuHx9mJhgIoHze4/WCjEZMDOrOCQ3xjyBwauBR9Si53hvD8ZFzCLk2ro=
